"""Entrypoint used by the GitHub Action.

Reads the PR event context that GitHub Actions provides automatically,
runs the review pipeline, and posts the result as a PR comment.
"""
from __future__ import annotations

import json
import os
import sys

from .github_client import GitHubClient
from .reviewer import ReviewAgent
from .schema import ReviewResult

SEVERITY_EMOJI = {"high": "\U0001F534", "medium": "\U0001F7E1", "low": "\u26AA"}


def format_comment(result: ReviewResult) -> str:
    lines = ["## \U0001F916 AI PR Review", ""]

    if result.failed_passes:
        skipped = ", ".join(result.failed_passes)
        plural = "es" if len(result.failed_passes) != 1 else ""

        lines.append(
            f"### \u26A0\uFE0F Review incomplete \u2014 {skipped} pass{plural} failed "
            "after retry and were skipped. Findings below are partial; check "
            "the skipped categories manually before merging."
        )
        lines.append("")
    lines.append(result.summary)
    lines.append("")

    if result.issues:
        lines.append("| | File | Category | Issue | Suggestion |")
        lines.append("|---|---|---|---|---|")
        for issue in result.issues:
            loc = f"{issue.file}:{issue.line}" if issue.line else issue.file
            lines.append(
                f"| {SEVERITY_EMOJI[issue.severity]} | `{loc}` | {issue.category} "
                f"| {issue.message} | {issue.suggestion or '\u2014'} |"
            )

    lines.append("")
    lines.append(f"**Verdict:** {result.verdict.replace('_', ' ')}")
    lines.append("")
    lines.append(
        "<sub>Generated by an automated review agent. Treat as a second pair "
        "of eyes, not a replacement for human review.</sub>"
    )
    return "\n".join(lines)


def get_pr_number() -> int:
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        raise RuntimeError("GITHUB_EVENT_PATH not set -- is this running inside GitHub Actions?")

    with open(event_path) as f:
        event = json.load(f)

    pr_number = event.get("pull_request", {}).get("number") or event.get("number")
    if not pr_number:
        raise RuntimeError("Could not find a PR number in the GitHub event payload.")
    return pr_number


def main() -> int:
    repo = os.environ["GITHUB_REPOSITORY"]
    github_token = os.environ["GITHUB_TOKEN"]
    pr_number = get_pr_number()

    client = GitHubClient(token=github_token, repo=repo)
    diff = client.get_pr_diff(pr_number)

    if not diff.strip():
        print("Empty diff -- nothing to review.")
        return 0

    agent = ReviewAgent()
    result = agent.review(diff)

    client.post_review_comment(pr_number, format_comment(result))

    print(f"Posted review with {len(result.issues)} issue(s). Verdict: {result.verdict}")
    return 1 if result.verdict in ("request_changes" , "incomplete") else 0


if __name__ == "__main__":
    sys.exit(main())
